insert into locations (name)
values  ('Victoria Falls'),
        ('Harare'),
        ('Chimanimani'),
        ('Masvingo'),
        ('Kadoma'),
        ('Hwange'),
        ('Norton'),
        ('Kwekwe'),
        ('Lupane'),
        ( 'Marondera'),
        ( 'Macheke'),
        ( 'Rusape'),
        ( 'Mutare'),
        ( 'Hot Springs'),
        ( 'Beatrice'),
        ( 'Mvuma'),
        ( 'Featherstone'),
        ( 'Chivhu');
